### ISSUE TITLE
Array conversion much slower than access via [:,:]

### ISSUE THREAD

**Issue by felixcremer** [meggart/DiskArrays.jl#26] opened 2021-04-23 08:26 UTC
When I want to convert my DiskArray into a normal memory Array, the conversion with Array is very slow compared to the getindex acess.
Is this something that we could fix in DiskArrays or is there a better method to do the conversion? 

```julia

julia> @time palfreqdata = palfreq[:,:]
  0.072899 seconds (157 allocations: 166.524 MiB)
5820×7500 Matrix{Float32}:
 1.0f32  1.0f32  1.0f32  1.0f32  1.0f32  …  1.0f32  1.0f32  1.0f32  1.0f32  1.0f32
 1.0f32  1.0f32  1.0f32  1.0f32  1.0f32     1.0f32  1.0f32  1.0f32  1.0f32  1.0f32
 1.0f32  1.0f32  1.0f32  1.0f32  1.0f32     1.0f32  1.0f32  1.0f32  1.0f32  1.0f32
 ⋮                                       ⋱  ⋮                               
 1.0f32  1.0f32  1.0f32  1.0f32  1.0f32     1.0f32  1.0f32  1.0f32  1.0f32  1.0f32
 1.0f32  1.0f32  1.0f32  1.0f32  1.0f32     1.0f32  1.0f32  1.0f32  1.0f32  1.0f32
 1.0f32  1.0f32  1.0f32  1.0f32  1.0f32     1.0f32  1.0f32  1.0f32  1.0f32  1.0f32

julia> @time Array(palfreq.data)
  9.528337 seconds (218.25 M allocations: 14.635 GiB, 21.90% gc time)
5820×7500 Matrix{Float32}:
 1.0f32  1.0f32  1.0f32  1.0f32  1.0f32  …  1.0f32  1.0f32  1.0f32  1.0f32  1.0f32
 1.0f32  1.0f32  1.0f32  1.0f32  1.0f32     1.0f32  1.0f32  1.0f32  1.0f32  1.0f32
 1.0f32  1.0f32  1.0f32  1.0f32  1.0f32     1.0f32  1.0f32  1.0f32  1.0f32  1.0f32
 ⋮                                       ⋱  ⋮                               
 1.0f32  1.0f32  1.0f32  1.0f32  1.0f32     1.0f32  1.0f32  1.0f32  1.0f32  1.0f32
 1.0f32  1.0f32  1.0f32  1.0f32  1.0f32     1.0f32  1.0f32  1.0f32  1.0f32  1.0f32
 1.0f32  1.0f32  1.0f32  1.0f32  1.0f32     1.0f32  1.0f32  1.0f32  1.0f32  1.0f32

```

**Comment by meggart** [comment] 2021-04-23 08:28
Do you have an idea which method is called for `Array`? Would be nice to see the call stack and check if there is single-element access/

**Comment by felixcremer** [comment] 2021-04-23 08:38
This is the stacktrace when I do an interrupt during the Array conversion:
```julia
julia> Array(palfreq.data)
^CERROR: InterruptException:
Stacktrace:
 [1] copyto_unaliased!(deststyle::IndexLinear, dest::Matrix{Float32}, srcstyle::IndexCartesian, src::YAXArrayBase.NetCDFVariable{Float32, 2})
   @ Base ./abstractarray.jl:975
 [2] copyto!
   @ ./abstractarray.jl:950 [inlined]
 [3] copyto_axcheck!
   @ ./abstractarray.jl:1056 [inlined]
 [4] Matrix{Float32}(x::YAXArrayBase.NetCDFVariable{Float32, 2})
   @ Base ./array.jl:540
 [5] Array(A::YAXArrayBase.NetCDFVariable{Float32, 2})
   @ Core ./boot.jl:472
 [6] top-level scope
   @ REPL[71]:1
```

I think, that it calls this codeblock in the end
```julia
            # Dual-index implementation
            i = idf - 1
            @inbounds for a in src
                dest[i+=1] = a
            end
        end
```
https://github.com/JuliaLang/julia/blob/fc02458492c60f6527245c6991f729c2a986f666/base/abstractarray.jl#L1024

**Comment by meggart** [comment] 2021-04-23 09:32
Ah, yes and this is indexing into every element which causes huge overhead. We should define a method for 
`Base.copyto!(dest::AbstractArray, src::AbstractDiskArray)`

**Comment by meggart** [comment] 2022-01-13 17:07
I am closing this as another duplicate of #44

**Closed by meggart** 2022-01-13 17:07 UTC
